name: 'Install Node Dependencies'
description: 'Install monorepo dependencies using yarn'
inputs:
  workingDirectory:
    description: 'The working directory in which the install should be performed'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: pwd
      run: pwd
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
    - name: cacheFolder
      run: yarn config get cacheFolder
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
    - name: Cache yarn cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Cache node modules
      uses: ./.github/actions/cache-node-modules
    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
