name: 'Get Project Code Changes'
description: 'Returns which projects have been modified'
inputs:
  base-branch:
    description: 'reference branch to compare current HEAD with'
    required: true
outputs:
  projects:
    description: Names of the projects being changed
    value: ${{ steps.affected-projects.outputs.projects }}
runs:
  using: 'composite'
  steps:
    - uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: ${{ inputs.base-branch }}

    - id: affected-projects
      run: echo "::set-output name=projects::$(npx nx print-affected | jq -c ".projects")"
      shell: bash
