on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['examples/swarmion-starter/**']

# cancel previous runs on the same PR
concurrency:
  group: ${{ github.ref }}.examples.swarmion-starter
  cancel-in-progress: true

name: ⛷ PR swarmion stater example

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash
    working-directory: examples/swarmion-starter

jobs:
  build:
    name: 🏗 Build Project
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
        with:
          workingDirectory: examples/swarmion-starter
