on:
  push:
    branches:
      - main

name: Deploy production
concurrency: push_main

permissions: write-all

env:
  CI: true

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Configure AWS credentials with assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Deploy production
        # nx run-many is used here, because it will not throw an error if our target action isn't found in the project, which is exactly what we want!
        run: pnpm nx run-many --target=deploy-production
        shell: bash
